### PR TITLE
VB.Net: Strict Mode, fixes #32

### LINKED ISSUE #32: VB.Net: Strict Mode
Hi, ```BC30209	Option Strict On requires all variable declarations to have an 'As' clause.``` is causing build to fail.

Any help would be appreciated, Thanks

### PR DESCRIPTION
**Pull request by wahmedswl**
Hi, previous pull request wrongly assigned String to $GitIsDirty$ but it is Boolean. So sorry about that

### CODE REVIEW

**Comment by kzu** [comment]
Could you rebase on top of master and resolve conflicts so I can merge?

Thanks!

**Comment by wahmedswl** [comment]
@kzu, rebased. thanks

**Comment by kzu** [comment]
Thanks!

**Comment by wahmedswl** [comment]
On Nuget, v1.1.56 is against this build? Is there any version mapping available?

Thanks

**Pull request merged**
